### ISSUE TITLE
Connect timed out が発生する

### ISSUE THREAD

**Issue by otanikohei** [jaws-ug-kanazawa/Runbook#11]
再発したので Issue としてお送りしておきます。

```
AdminSwitchRole:~/environment $ sudo ln -s /usr/bin/pip-3.6 /usr/bin/pip3
ln: failed to create symbolic link '/usr/bin/pip3': File exists
AdminSwitchRole:~/environment $ /usr/bin/pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
AdminSwitchRole:~/environment $ python3 -V
Python 3.6.9
AdminSwitchRole:~/environment $ pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
AdminSwitchRole:~/environment $ sudo pip3 install AWSIoTPythonSDK
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting AWSIoTPythonSDK
  Downloading https://files.pythonhosted.org/packages/8c/33/06f4ad288d85194a43b59f6103e5c78b289095dffce14cf45a914e541628/AWSIoTPythonSDK-1.5.2-py2.py3-none-any.whl (79kB)
    100% |████████████████████████████████| 81kB 5.6MB/s 
Installing collected packages: AWSIoTPythonSDK
Successfully installed AWSIoTPythonSDK-1.5.2
AdminSwitchRole:~/environment $ wget http://bit.ly/2QggRgx -O dummyclient.tar.gz
--2022-06-16 05:49:51--  http://bit.ly/2QggRgx
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s3-ap-northeast-1.amazonaws.com/awsj-iot-handson/data-collection/dummyclient.tar.gz [following]
--2022-06-16 05:49:52--  https://s3-ap-northeast-1.amazonaws.com/awsj-iot-handson/data-collection/dummyclient.tar.gz
Resolving s3-ap-northeast-1.amazonaws.com (s3-ap-northeast-1.amazonaws.com)... 52.219.136.42
Connecting to s3-ap-northeast-1.amazonaws.com (s3-ap-northeast-1.amazonaws.com)|52.219.136.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5046 (4.9K) [application/x-gzip]
Saving to: ‘dummyclient.tar.gz’

dummyclient.tar.gz                  100%[==================================================================>]   4.93K  --.-KB/s    in 0s      

2022-06-16 05:49:52 (57.4 MB/s) - ‘dummyclient.tar.gz’ saved [5046/5046]

AdminSwitchRole:~/environment $ tar -zxvf dummyclient.tar.gz
DummyDevice/
DummyDevice/deviceMain.py
DummyDevice/dependency.py
DummyDevice/certs/
DummyDevice/certs/root.pem
DummyDevice/iotCommon.py
AdminSwitchRole:~/environment $ cd ~/environment/DummyDevice/
AdminSwitchRole:~/environment/DummyDevice $ python3 deviceMain.py --device_name 20220619things --endpoint a3ul1zhtx9l2d0-ats.iot.ap-northeast-1.amazonaws.com
start >>>
device_name: 20220619things
endpoint: a3ul1zhtx9l2d0-ats.iot.ap-northeast-1.amazonaws.com
rootca cert: ./certs/root.pem
private key: ./certs/private.pem
certificate: ./certs/2c019bb79c79e07965a4e7d9a9bb4e2f2fb6bd2c887d6dd7d2adbed4ca8c9d27-certificate.pem.crt
connect to AWS IoT >>>
Connect timed out
class shadow Error
Error main()
Traceback (most recent call last):
  File "deviceMain.py", line 48, in device_main
    iot_client.create_shadow()
  File "/home/ubuntu/environment/DummyDevice/iotCommon.py", line 136, in create_shadow
    raise e
  File "/home/ubuntu/environment/DummyDevice/iotCommon.py", line 122, in create_shadow
    self._shadow_client.connect(self.KEEPALIVE)
  File "/usr/local/lib/python3.6/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 1278, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python3.6/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 520, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python3.6/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 199, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException

AdminSwitchRole:~/environment/DummyDevice $ pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
AdminSwitchRole:~/environment/DummyDevice $ 
```

**Comment by matyuda** [comment]
Connect timed out が発生した場合には、モノを再作成する方法をワークアラウンドとして手順書へ掲載する
